### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by junglejuz** [artumino/VRScreenCap#29]
VRScreencap doesn't launch for me.
Nothing happens at all when trying to open version 0.3.1.
When trying to open version 0.4.0-dev5 I can see an entry appear in the task manager processes list for about 0.5 sec, then it disappears again. Nothing is in the system tray.

[output.log](https://github.com/artumino/VRScreenCap/files/12723338/output.log)

**Comment by artumino** [comment]
Hi, ERROR_FORM_FACTOR_UNAVAILABLE should be reported by the runtime only if the headset is unavailable.
I published a newer build (4.0.0-dev7) that waits for it to become available instead of exiting right away.
Let me know if it works or if it keeps waiting for the headset.  I'm not sure why this isn't the case in older releases.

**Comment by junglejuz** [comment]
It's now opening and visible in the system tray, however when steamvr auto-launches nothing appears inside... just the steamvr virtual environment. If I set oculus as the default openxr runtime it doesn't go into vr mode at all. (I have katanga_VR set as the direct mode for geo11.)

Also the Settings menu item is greyed out.
[output.log](https://github.com/artumino/VRScreenCap/files/12738996/output.log)
